name: Python CI - Test & Coverage to SonarCloud and SonarQube

on:
  push:
    branches: ["**"] # Executa em qualquer push
  pull_request:
    branches: ["**"] # Executa em qualquer PR

jobs:
  build_and_lint:
    name: Build, Install Dependencies & Flake8 Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # Ativa o cache de dependências

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov

      - name: Run Flake8 checks
        # O Flake8 por padrão busca o setup.cfg na raiz do projeto.
        run: |
          source .venv/bin/activate
          flake8 etl_taiga/ --exclude=.venv --config=setup.cfg

  unit_tests:
    name: Unit Tests with Coverage
    runs-on: ubuntu-latest
    needs: build_and_lint # Agora depende da job que também fez o lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pytest pytest-cov  

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          pytest etl_taiga/tests --cov=etl_taiga --cov-report=xml:coverage.xml --cov-report=term

      - name: Ensure coverage.xml exists
        run: |
          if [ ! -f coverage.xml ]; then
            echo "coverage.xml not found!"
            exit 1
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: unit_tests # Depende de unit_tests para ter o coverage.xml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: .

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=iNineBD_Track-5Sem2025ETL
            -Dsonar.organization=ininetrack
            -Dsonar.projectName=Track-5Sem2025ETL
            -Dsonar.sources=etl_taiga
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=etl_taiga/tests/**
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.verbose=true

  sonarqube:
    name: SonarQube (Self-Hosted)
    runs-on: ubuntu-latest
    needs: unit_tests # Depende de unit_tests para ter o coverage.xml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: .

      - name: SonarQube Scan (Self-hosted)
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR2_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Track-5Sem2025ETL
            -Dsonar.projectName=Track-5Sem2025ETL
            -Dsonar.sources=etl_taiga
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=etl_taiga/tests/**
            -Dsonar.host.url=http://144.22.212.19:9001
            -Dsonar.verbose=true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [sonarqube, sonarcloud] # Ou o nome do seu job de teste principal, talvez 'sonarcloud' ou 'sonarqube' se quiser que o deploy só ocorra após a análise de código
    steps:
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Remote Server to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Git Pull on Remote Server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /app/Track-5Sem2025ETL
            git pull origin $(git rev-parse --abbrev-ref HEAD)
          EOF