name: Python CI - Test & Coverage to SonarCloud and SonarQube

on:
  push:
    branches: ["**"]   # Executa em qualquer push
  pull_request:
    branches: ["**"]   # Executa em qualquer PR

jobs:
  build:
    name: Build & Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov

  unit_tests:
    name: Unit Tests with Coverage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: pytest etl_taiga/tests --cov=etl_taiga --cov-report=xml:coverage.xml --cov-report=term

      - name: Ensure coverage.xml exists
        run: |
          if [ ! -f coverage.xml ]; then
            echo "coverage.xml not found!"
            exit 1
          fi

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=iNineBD_Track-5Sem2025ETL
            -Dsonar.organization=ininetrack
            -Dsonar.projectName=Track-5Sem2025ETL
            -Dsonar.sources=etl_taiga
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=etl_taiga/tests/**
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.verbose=true

  sonarqube:
    name: SonarQube (Self-Hosted)
    runs-on: ubuntu-latest
    needs: unit_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: SonarQube Scan (Self-hosted)
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR2_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Track-5Sem2025ETL
            -Dsonar.projectName=Track-5Sem2025ETL
            -Dsonar.sources=etl_taiga
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=etl_taiga/tests/**
            -Dsonar.host.url=http://144.22.212.19:9001
            -Dsonar.verbose=true
