name: Python ETL CI with SonarCloud

on:
  push:
    branches: [main, sprint-1, sprint-2, sprint-3]
  pull_request:
    branches: [main, sprint-1, sprint-2, sprint-3]

jobs:
  build-and-test:
    name: Build, Test & Sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # Clona o repositório com histórico completo para análise
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para análise completa do Git e SonarCloud

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Definindo a versão do Python para 3.10
          cache: "pip" # Habilitando o cache do pip para acelerar as instalações de dependências

      - name: Install dependencies # Instala as dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify dependencies installation
        run: pip list

      - name: Set PYTHONPATH # Define o PYTHONPATH para incluir o diretório raiz do projeto
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run tests with coverage # Executa Pytest e gera relatório de cobertura em XML (para SonarCloud)
        run: |
          mkdir -p etl_taiga/coverage
          pytest --cov=etl_taiga --cov-report=xml:coverage/coverage.xml

      - name: SonarCloud Scan # Executa análise no SonarCloud com suporte à cobertura de testes
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=iNineBD_Track-5Sem2025ETL
            -Dsonar.organization=ininetrack
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=etl_taiga
            -Dsonar.exclusions=etl_taiga/tests/**
            -Dsonar.python.coverage.reportPaths=coverage/coverage.xml
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
