# Nome do workflow exibido na aba "Actions" do GitHub
name: SonarCloud Analysis

# Define os eventos que disparam esse workflow
on:
  push:
    branches:
      - main                        # Só dispara quando houver push para a branch 'main'
    paths-ignore:
      - '**.md'                     
      # Ignora mudanças em arquivos Markdown (ex: README.md)
      # Observação: o comentário abaixo diz que este workflow será executado somente
      # quando for feito merge de sprint-1, sprint-2 ou sprint-3 para main
      # Essa lógica é tratada abaixo com o filtro `if:` baseado na mensagem do commit
jobs:
  sonarcloud:
    # Condição extra: só roda se o push for um merge commit vindo de uma das branches sprint-1, 2 ou 3
    if: startsWith(github.event.head_commit.message, 'Merge pull request') && (
          contains(github.event.head_commit.message, 'sprint-1') ||
          contains(github.event.head_commit.message, 'sprint-2') ||
          contains(github.event.head_commit.message, 'sprint-3')
        )
    runs-on: ubuntu-latest   # Ambiente de execução: Ubuntu fornecido pelo GitHub

    steps:
      # Etapa 1: Clonar o repositório na máquina runner
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Etapa 2: Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Usa o Python 3.10
          cache: "pip"            # Ativa cache do pip para acelerar execuções futuras

      # Etapa 3: Instalar dependências do projeto + pytest e cobertura
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel cython  # Atualiza pip e ferramentas de build
          pip install -r requirements.txt   

      # Etapa 4: Define o PYTHONPATH corretamente para permitir importações do projeto
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Debug workspace structure
        run: |
          echo "PWD: $(pwd)"
          find . -type f

      # Etapa 5: Executar testes e gerar o relatório de cobertura em XML (requerido pelo SonarCloud)
      - name: Run tests with coverage
        run: pytest etl_taiga/tests --cov=etl_taiga --cov-report=xml:coverage.xml --cov-report=term 
          
        # pytest .\                     # Executa os testes localizados no diretório 'etl_taiga/tests'
        #         --cov=etl_taiga \                     # Coleta cobertura do pacote 'etl_taiga'
        #         --cov-report=xml:coverage.xml \       # Gera o relatório de cobertura em formato XML (para o SonarCloud)
        #         --cov-report=term                     # Também exibe um resumo no terminal
        #  working-directory: ${{ github.workspace }}/Track-5Sem2025ETL

      # Etapa 6: Garantir que o arquivo de cobertura foi gerado
      - name: Check coverage.xml existence
        run: |
          if [ ! -f coverage.xml ]; then
            echo "coverage.xml not found!"
            exit 1
          fi
      
      # Etapa 6: Executar a análise estática do código no SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Token secreto de autenticação do SonarCloud
        with:
          args: >
            -Dsonar.projectKey=iNineBD_Track-5Sem2025ETL
            -Dsonar.organization=ininetrack
            -Dsonar.projectName=Track-5Sem2025ETL
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=etl_taiga
            -Dsonar.sourceEncoding=UTF-8 
            -Dsonar.exclusions=etl_taiga/tests/**
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.branch.name=main
            -Dsonar.verbose=true
