name: SonarCloud Analysis

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
    # Executa somente se o push veio de merge de uma das branches sprint-1, sprint-2 ou sprint-3
    # Isso é tratado na etapa de verificação do nome da branch anterior (ver abaixo)

jobs:
  sonarcloud:
    if: startsWith(github.event.head_commit.message, 'Merge pull request') && (
          contains(github.event.head_commit.message, 'sprint-1') ||
          contains(github.event.head_commit.message, 'sprint-2') ||
          contains(github.event.head_commit.message, 'sprint-3')
        )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests and generate coverage report
        run: |
          pytest --cov=etl_taiga --cov-report=xml:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=iNineBD_Track-5Sem2025ETL
            -Dsonar.organization=ininetrack
            -Dsonar.projectName=Track-5Sem2025ETL
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=etl_taiga
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=etl_taiga/tests/**
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.verbose=true