name: Python Linting

on:
    push:
      branches:
          - 'feature/**'
          - 'fix/**'
          - 'hotfix/**'
          - 'release/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Definindo a versão do Python para 3.10
          cache: "pip" # Habilitando o cache do pip para acelerar as instalações de dependências

      - name: Install dependencies # Instalando todos os pacotes necessários usando lista do repositório.
        run: |
          python -m pip install --upgrade pip setuptools wheel cython
          pip install -r requirements.txt

      - name: Run Flake8 linting # Rodando o Flake8 no diretório atual
        run: |
          flake8 etl_taiga

      - name: Run Pytest for Code Coverage and save to file # Rodando o PyTest apenas para gerar a cobertura de código e salvar em arquivo HTML
        run: |
          pytest --maxfail=1 --disable-warnings --cov=etl_taiga --cov-report=html:coverage_report # Salva o relatório de cobertura em 'coverage_report'

      - name: Upload coverage report # Fazendo upload do diretório de cobertura gerado
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage_report